name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Requirements
      run: |
        sudo apt install python3-virtualenv
        virtualenv -p python3 venv
        . venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt
