name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: docker.io/tumeda/tvm_tumeda:latest
    steps:
    - uses: actions/checkout@v2

    - name: Requirements
      run: |
        sudo apt update
        sudo apt install -y python3-virtualenv
        virtualenv -p python3 venv
        . venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Test
      run: |
        . venv/bin/activate
        cd tests
        ./run_all.sh
